# Generated by Django 4.2.16 on 2024-11-04 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_note'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
