# Generated by Django 4.2.16 on 2024-11-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
