# Generated by Django 4.2.16 on 2024-11-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_gamescore_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='iteration',
            field=models.IntegerField(default=0),
        ),
    ]
