# Generated by Django 4.2.16 on 2024-11-09 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_gamescore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='hard_mode',
            field=models.BooleanField(default=False),
        ),
    ]
